# SPARK network diagram https://www.ibm.com/docs/en/zpfas/1.1.0?topic=spark-configuring-networking-apache

version: '3.9'
services:
  master-node:
    image: hadooptest
    build: .
    hostname: master-node
    ports:
      - "7077:7077" # Spark master
      - "8080:8080" # Master web GUI
      - "9000:9000" # Hadoop NameNode
      - "9870:9870" # HDFS datanode web GUI
    command: bash -c "./hadoop-3.3.4/bin/hdfs namenode -format && ./hadoop-3.3.4/bin/hdfs --daemon start namenode && ./hadoop-3.3.4/bin/hdfs --daemon start datanode && jps && sleep 99999d"
    # ./hadoop-3.3.4/bin/hdfs namenode -format && 
    networks:
      - spark-network
    volumes:
      - hdfs-data:/hdfs-volume

networks:
  spark-network: {}

volumes:
  hdfs-data:
